# ---- Assets: carrega as principais imagens do jogo.
import pygame
from parametros import WIDTH, HEIGHT, CHAR_HEIGHT, CHAR_WIDTH

def load_assets():
    ''' Assets: dicionario que carrega as principais imagens e presonagens do jogo'''

    assets = {}
    assets["background"] = pygame.image.load('Dungeons/fundonormal.png').convert()
    assets["background"] = pygame.transform.scale(assets["background"], (WIDTH, HEIGHT))
    assets["antes_fase_1"] = pygame.image.load('Dungeons/antes_fase_1.png').convert()
    assets["antes_fase_1"] = pygame.transform.scale(assets["antes_fase_1"], (WIDTH, HEIGHT))
    assets["tela_pre_3"] = pygame.image.load('Dungeons/tela_pre_3.png').convert()
    assets["tela_pre_3"] = pygame.transform.scale(assets["tela_pre_3"], (WIDTH, HEIGHT))
    assets["tela_pre_2"] = pygame.image.load('Dungeons/tela_pre_2.png').convert()
    assets["tela_pre_2"] = pygame.transform.scale(assets["tela_pre_2"], (WIDTH, HEIGHT))
    assets["tela_pre_boss"] = pygame.image.load('Dungeons/sala_pre_boss.png').convert()
    assets["tela_pre_boss"] = pygame.transform.scale(assets["tela_pre_boss"], (WIDTH, HEIGHT))
    assets["gameover"] = pygame.image.load('Dungeons/gameover.png').convert()
    assets["gameover"] = pygame.transform.scale(assets["gameover"], (WIDTH, HEIGHT))
    assets["tela_win"] = pygame.image.load('Dungeons/tela_win.png').convert()
    assets["tela_win"] = pygame.transform.scale(assets["tela_win"], (WIDTH, HEIGHT))
    assets['Tela_introducao'] = pygame.image.load('Dungeons/Tela_introducao.png').convert()
    assets['Tela_introducao'] = pygame.transform.scale(assets["Tela_introducao"], (WIDTH, HEIGHT))
    assets["telainicio1"] = pygame.image.load('Dungeons/telainicio1.png').convert()
    assets["telainicio1"] = pygame.transform.scale(assets["telainicio1"], (WIDTH, HEIGHT))
    assets["fundotela3"] = pygame.image.load('Dungeons/fundotela3.png').convert_alpha()
    assets["fundotela3"] = pygame.transform.scale(assets["fundotela3"], (WIDTH, HEIGHT))
    assets["char_img"]= pygame.image.load('Dungeons/teste_heroi_2.png').convert_alpha()
    assets["char_img"] = pygame.transform.scale(assets["char_img"], (CHAR_WIDTH, CHAR_HEIGHT))
    assets["char_atacc"] = pygame.image.load('Dungeons/teste_heroi.png').convert_alpha()
    assets["char_atacc"] = pygame.transform.scale(assets["char_atacc"], (CHAR_WIDTH, CHAR_HEIGHT))
    assets["mob_atacc"] = pygame.image.load('Dungeons/mob_certo.png').convert_alpha()
    assets["mob_atacc"] = pygame.transform.scale(assets["mob_atacc"], (CHAR_WIDTH - 25, CHAR_HEIGHT-40))
    assets["mob_normal"] = pygame.image.load('Dungeons/sprite_2_mob.png').convert_alpha()
    assets["mob_normal"] = pygame.transform.scale(assets["mob_normal"], (CHAR_WIDTH - 25, CHAR_HEIGHT-40))
    assets["mob_atacc2"] = pygame.image.load('Dungeons/sprite_2_mob_vermelho_1.png').convert_alpha()
    assets["mob_atacc2"] = pygame.transform.scale(assets["mob_atacc2"], (CHAR_WIDTH - 25, CHAR_HEIGHT-40))
    assets["mob_normal2"] = pygame.image.load('Dungeons/sprite_2_mob_vermelho.png').convert_alpha()
    assets["mob_normal2"] = pygame.transform.scale(assets["mob_normal2"], (CHAR_WIDTH - 25, CHAR_HEIGHT-40))
    assets["arqueiro"] = pygame.image.load('Dungeons/mob_arco.png').convert_alpha()
    assets["arqueiro"] = pygame.transform.scale(assets["arqueiro"], (CHAR_WIDTH - 25, CHAR_HEIGHT-40))
    assets["flecha"] = pygame.image.load('Dungeons/flecha.png').convert_alpha()
    assets["flecha"] = pygame.transform.scale(assets["flecha"], (100, 50))
    assets["boss"] = pygame.image.load('Dungeons/boss_bola_de_fogo.png').convert_alpha()
    assets["boss"] = pygame.transform.scale(assets["boss"], (CHAR_WIDTH+10, CHAR_HEIGHT+20))
    assets["fundo_boss"] = pygame.image.load('Dungeons/fundo_boss.png'). convert_alpha()
    assets["fundo_boss"] = pygame.transform.scale(assets["fundo_boss"], (WIDTH, HEIGHT))
    assets["fundo2"] = pygame.image.load('Dungeons/fundo2.png').convert_alpha()
    assets["fundo2"] = pygame.transform.scale(assets["fundo2"], (WIDTH, HEIGHT))
    assets["bola_de_fogo"] = pygame.image.load('Dungeons/bola_de_fogo.png').convert_alpha()
    assets["bola_de_fogo"] = pygame.transform.scale(assets["bola_de_fogo"], (100, 50))
    assets["score_font"] = pygame.font.Font('Dungeons/OldLondon.ttf', 28)
    assets["score_font2"] = pygame.font.Font('Dungeons/PressStart2P.ttf', 28)
    return assets
